APPLICATION = test_bme68x
BOARD ?= berta-h10
RIOTBASE ?= $(CURDIR)/../RIOT
LORA3ABASE ?= $(CURDIR)/../lora3a-boards
EXTERNAL_BOARD_DIRS += $(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS += $(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS += $(LORA3ABASE)/pkg
QUIET ?= 1
DEVELHELP ?= 1
PORT ?= /dev/ttyUSB0

USEMODULE += periph_i2c
USEMODULE += printf_float
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec
USEMODULE += bme68x bme68x_i2c bme68x_fp
# needed for floating point
CFLAGS += -DTHREAD_STACKSIZE_DEFAULT=2048

CFLAGS += -DACME0_BUS_MODE=MODE_I2C -DACME1_BUS_MODE=MODE_I2C -DACME2_BUS_MODE=MODE_I2C
SENSOR1 := "{.ifsel=BME68X_I2C_INTF,.intf.i2c.dev=ACME0_I2C_DEV,.intf.i2c.addr=BME68X_I2C_ADDR_1}"
SENSOR2 := "{.ifsel=BME68X_I2C_INTF,.intf.i2c.dev=ACME0_I2C_DEV,.intf.i2c.addr=BME68X_I2C_ADDR_2}"
SENSOR3 := "{.ifsel=BME68X_I2C_INTF,.intf.i2c.dev=ACME1_I2C_DEV,.intf.i2c.addr=BME68X_I2C_ADDR_1}"
SENSOR4 := "{.ifsel=BME68X_I2C_INTF,.intf.i2c.dev=ACME1_I2C_DEV,.intf.i2c.addr=BME68X_I2C_ADDR_2}"
SENSOR5 := "{.ifsel=BME68X_I2C_INTF,.intf.i2c.dev=ACME2_I2C_DEV,.intf.i2c.addr=BME68X_I2C_ADDR_1}"
SENSOR6 := "{.ifsel=BME68X_I2C_INTF,.intf.i2c.dev=ACME2_I2C_DEV,.intf.i2c.addr=BME68X_I2C_ADDR_2}"
CFLAGS += -DBME68X_PARAMS_I2C="${SENSOR1},${SENSOR2},${SENSOR3},${SENSOR4},${SENSOR5},${SENSOR6}"

include $(RIOTBASE)/Makefile.include
