APPLICATION = test_bme68x
BOARD ?= berta-h10
RIOTBASE ?= $(CURDIR)/../RIOT
LORA3ABASE ?= $(CURDIR)/../lora3a-boards
EXTERNAL_BOARD_DIRS += $(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS += $(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS += $(LORA3ABASE)/pkg
QUIET ?= 1
DEVELHELP ?= 1
PORT ?= /dev/ttyUSB0

USEMODULE += periph_i2c
USEMODULE += printf_float
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec
USEMODULE += bme68x
USEMODULE += bme68x_i2c
USEPKG += bme68x

CFLAGS += -DENABLE_ACME2=1
CFLAGS += -DACME1_BUS_MODE=MODE_I2C
CFLAGS += -DACME2_BUS_MODE=MODE_I2C

include $(RIOTBASE)/Makefile.include
